    - name: Remove Existing App Location
      ansible.builtin.file:
        path: "{{ app_location }}"
        state: absent
      ignore_errors: true
    
    - name: create App directory
      ansible.builtin.file:
        name: /app
        state: directory 
   
    - name: "Download Application code {{ component }}"
      ansible.builtin.unarchive:
        src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip"
        dest: "{{ app_location }}"
        remote_src: yes
 
    